services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/project
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db 
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: